name: connect-to-github
on:
  schedule:
    - cron: '0 0 */13 * *'

jobs:
  start_test_job:
    runs-on: self-hosted
    steps:
      - name: "Start VM"
 #       run: gcloud compute instances start github-actions-runner-1 --zone australia-southeast-b
 #     - name: "Sleep for 30 seconds"
 #       run: sleep 60s
 #       shell: bash
 #     - name: "Stop VM"
 #       run: gcloud compute instances stop github-actions-runner-1 --zone australia-southeast-b
